[package]
name = "xb3_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.30", features = [ "derive" ]}
binary-reader = "0.4.5"
binary_rw = "4.0.4"